services:
  dev-db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=dev
    ports:
      - 3306:3306
    volumes:
      - reefTMS-dev-data:/var/lib/mysql/
  adminer:
    image: adminer
    ports:
      - 8081:8080

volumes:
  reefTMS-dev-data:
